inherit_from:
  - .rubocop_airbnb.yml

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
  TargetRubyVersion: 2.5

Rails/HelperInstanceVariable:
  Enabled: false

Metrics/LineLength:
  Max: 120

Airbnb/RiskyActiverecordInvocation:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false